project_id = "yfrheruufeqoflpozxba"

[functions.paystack]
verify_jwt = false

[functions.generate-certificate]
verify_jwt = false

[functions.evaluate-assignment]
verify_jwt = false

[functions.send-followups]
verify_jwt = false

[functions.student-chatbot]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-admin]
verify_jwt = true
